### PR TITLE
fixed name and changed twitter handle for GIS

### PR DESCRIPTION
**Pull request by jonathangoeke**
I fixed the name of GIS (Genome Institute of Singapore), and I added the Twitter handle for our Institute

### CODE REVIEW

**Comment by drpatelh** [comment]
I think it's probably best that we add yourself as the main contact too seeing as Andreas no longer works at the Institute. Ping @ewels @apeltzer.

**Comment by jonathangoeke** [comment]
> I think it's probably best that we add yourself as the main contact too seeing as Andreas no longer works at the Institute. Ping @ewels @apeltzer.

sure should I change that?

**Comment by drpatelh** [comment]
Yep. Assuming the email address won't work either so probably best to update it whilst you are making these changes. Just wanted to double-check with the other core members because Andreas was quite heavily involved in setting up nf-core. I think they will agree though so should be fine :+1:

**Comment by apeltzer** [comment]
Yes please adjust this. I doubt Andreas will mind that 👍

**Comment by ewels** [comment]
@andreas-wilm - all ok I assume?

**Comment by jonathangoeke** [comment]
I spoke with Andreas, he is fine with that. I can also add @shihcc and me if 2 main contacts are OK?

**Comment by apeltzer** [comment]
Normally we have only one contact person per institute - its anyways rarely happening that you're contacted via this, so should be fine to have you on it alone 👍

**Comment by jonathangoeke** [comment]
ok done!

**Pull request merged**
