### PR TITLE
Fix broken events page

### PR DESCRIPTION
**Pull request by ewels**
* Properly parse only the front-matter as YAML instead of the whole markdown file
* Add CSS classes to tables for nicer formatting

### CODE REVIEW

**Comment by mashehu** [comment]
Can you maybe add one check to not show an empty "Location:" in the `header_html` if not set.

**Comment by ewels** [comment]
Good spot 👍

**Comment by ewels** [comment]
Ok, fixed - added a few additional tweaks to the markdown rendering too.

**Comment by mashehu** [comment]
Interesting choice for location 🙂

**Comment by ewels** [comment]
> Interesting choice for location 🙂

It was an aesthetic thing - I didn't like the empty space! 😅

**Pull request merged**
