### PR TITLE
Add docker

### LINKED ISSUE #446: Website Docker image
At the moment it's a bit of a hassle for people to test out PRs on the website. You need to set up a LAMP / MAMP / WAMP server locally which can put newcomers off.

Even though we won't use it in production, it could be nice to have a simple Docker container to run a server for people to test PRs. Thinking about it, it will have to mount a checked-out version of the code for this, so we can presumably use an existing Docker container and just write an example command in the docs / Readme about how to do this.

Any suggestions / previous experience?

### PR DESCRIPTION
**Pull request by mashehu**
After (partially) running all the php update scripts (see README.md, but no worries if they throw endless errors 🙂), run `docker-compose up` and go to `http://localhost:8888/` to see the website.

Closes #446.

### CODE REVIEW

**Comment by MaxUlysse** [comment]
```
> docker-compose up
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/home/maxime/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/maxime/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/maxime/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/maxime/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 11, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by MaxUlysse** [comment]
Nevermind, I actually just tried to do the `docker-compose up` part without trying to set up the rest beforehand...
:facepalm:

**Comment by MaxUlysse** [comment]
Ok so ran all the php update scripts, and still fot the same error.

**Comment by MaxUlysse** [comment]
OK, so as discussed on Slack, my issue was about a bad docker-compose version.

Once you actually have the right tool, and actually follow all instructions, it works perfectly.
Amazing work @mashehu

**Comment by apeltzer** [comment]
Locally tested here fine as well - looks like much easier testing is now possible, ❤️  it :-)

**Comment by ewels** [comment]
Nice! 🚀

**Comment by ewels** [comment]
Might have to start copying this into all of my website repos 😅

**Pull request merged**
