### PR TITLE
updating the example outputs to nf-core/tools version 2.3

### PR DESCRIPTION
**Pull request by varunshamanna**
I have updated the markdown/developers/ [adding_modules.md]

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1097"></a>

### CODE REVIEW

**Comment by mashehu** [comment]
found another old remnant: https://github.com/nf-core/nf-co.re/pull/1097/commits/900d25bf1498ff91db093fa3780a71b8ce5c8a4b

**Review by mashehu — APPROVED** [review]

**Comment by mashehu** [comment]
We will hopefully release another version of tools soon. I will update the numbers accordingly.

**Comment by ewels** [comment]
> We will hopefully release another version of tools soon. I will update the numbers accordingly.

I think that this is basically always going to be the case 😅  I gave up trying to keep these examples up to date a while back.. We have talked about automating it, but honestly I'm not sure it's worth the effort.

Personally I'm happy to merge as-is and continue updating these ad-hoc 👍🏻

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Review by mashehu — APPROVED** [review]

**Pull request merged**
