### PR TITLE
Improved format of Glossary section in training_material.md

### PR DESCRIPTION
**Pull request by atoffano**
Fixes formatting issue with the Glossary section of training_material.md on the webpage by changing the bullet point formatting to ensure correct display of bulleted list online.

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1678"></a>

### CODE REVIEW

**Comment by FranBonath** [comment]
@nf-core-bot fix linting

**Comment by sofstam** [comment]
Unless I miss something, I cannot see any changed files in this PR.

**Comment by atoffano** [comment]
Apparently automatic linting reverted the changes i made.
The classic linting seems to prevent the rendering of bullet points inside </details> containers on the website, though it works in a normal .md.
I'm unsure of how to fix this without circumventing automatic linting or removing the </details> container..

**Comment by sofstam** [comment]
Screenshot 2023-03-29 at 16 14 42
This is how it looks like for me. Can you maybe try and add the files again in the PR?

**Pull request closed without merging**
