### PR TITLE
add contributor CMGG

### PR DESCRIPTION
**Pull request by matthdsm**

### CODE REVIEW

**Comment by mashehu** [comment]
Hi, can you please also add a white variant of the logo, which we use for dark backgrounds?

**Comment by matthdsm** [comment]
Should be OK!

**Comment by matthdsm** [comment]
Whoops, had a typo in the hex codes!

**Review by mashehu — APPROVED** [review]
Looks good now!

**Comment by matthdsm** [comment]
Great, thanks for the review!

**Pull request merged**
