### PR TITLE
Added new WIBR logos 

### PR DESCRIPTION
**Pull request by chlazaris**

### CODE REVIEW

**Comment by mashehu** [comment]
Your logo with the light theme was still not vectorized. I made a PR to your repo with a corrected version https://github.com/chlazaris/nf-co.re/pull/1

**Comment by chlazaris** [comment]
Thank you very much for your help with this, @mashehu

I have now pulled the request.

Best Regards,

Harris

**Comment by ewels** [comment]
x-ref: https://github.com/nf-core/nf-co.re/pull/584#issuecomment-745806232

**Comment by apeltzer** [comment]
Is this now good to go @ewels - I'm not getting whether its already correct format now...

**Review by mashehu — APPROVED** [review]

**Comment by mashehu** [comment]
Tested locally and works there. I'll merge it now.

**Pull request merged**
