### PR TITLE
Fix link to pipeline stats

### LINKED ISSUE #798: Links on global nf-core pipeline stats table are broken
**Describe the bug**
Links on global nf-core pipeline stats table are broken (404)

**To Reproduce**

Click on any of the pipeline links on https://nf-co.re/stats#repo_traffic

**Expected behavior**
Sent to a stats page

**Screenshots**

**Browser (please complete the following information):**

**Additional context**
Was moved to a different page: https://nfcore.slack.com/archives/CE7DN1U7M/p1623408664033000

### PR DESCRIPTION
**Pull request by jfy133**
From the global nf-core pipeline status page.

Note this is NOT tested as I couldn't get the whole `config.ini` and then `php` stuff to work, but I think it's a simple enough fix :grimacing: 

To close #798

### CODE REVIEW

**Review by ewels — APPROVED** [review]
LGTM!

**Comment by ewels** [comment]
Thanks! Shouldn't need PHP installed etc, `docker compose up` should run the site locally without any other setup..

**Comment by jfy133** [comment]
> Thanks! Shouldn't need PHP installed etc, `docker compose up` should run the site locally without any other setup..

Hm, ok well when I ran `docker compose up` the pipeline table wasn't propgated with any pipeline? So from the documentation I assumed I had to run the various scripts to pull the latest info of each pipeline?

**Comment by ewels** [comment]
Ah right, yeah. Ok you might be right that you need the ini stuff for this then 🤔 Can't remember if these calls use authentication or not. Sorry, my bad 👌🏻

**Pull request merged**
