### PR TITLE
Add Cancer Research UK Manchester Institute to the organisation list

### PR DESCRIPTION
**Pull request by SPPearce**
Add Cancer Research UK Manchester Institute to the organisation list.

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1242"></a>

### CODE REVIEW

**Comment by mashehu** [comment]
We also need a white version of the logo (to use for the dark theme)

**Comment by ewels** [comment]
Nudge for @SPPearce in case you missed this ☝🏻

**Comment by SPPearce** [comment]
Yeah, I saw it, I just don't have a white version of the logo to hand.

**Comment by ewels** [comment]
Ah ok - we have [CRUK Beatson](https://nf-co.re/community#beatson-institute-institute-of-cancer-sciences) already, pretty sure I faffed around making their white logo years ago. I'll see if I can make a white version for you quickly in Illustrator 👍🏻

**Comment by ewels** [comment]
Added 👍🏻

**Review by ewels — APPROVED** [review]
Looks good!

image
image

**Comment by SPPearce** [comment]
Thanks Phil! I have no experience of illustrator to do it myself. Looks
good though.

**Pull request merged**
