### PR TITLE
nf-core Launch GUI

### PR DESCRIPTION
**Pull request by ewels**
Web implementation of the graphical user interface for launch Nextflow workflows using `nf-core launch`.

Functionality for running this from a https://nf-co.re pipeline page is planned and basically built in and ready to go, but I need to go to bed so that will come in a future PR or be tacked on to this one later next week.

See Slack for screen capture demos: https://nfcore.slack.com/archives/CUC8PPDL2/p1593212486143900

### CODE REVIEW

**Comment by ewels** [comment]
Note that a speedy merge would be kind of nice, as it'll make it easier for people to test when it's running on the main site.

Happy to take suggestions and improvements up as comments here before or after merge, can push in a new PR if necessary.

**Comment by apeltzer** [comment]
Did I hear 
> a speedy merge
would be nice? 

Bildschirmfoto 2020-06-27 um 10 43 12

**Comment by ewels** [comment]
Yeah I don't really expect many people / anyone to seriously pick through 800 lines of PHP and JavaScript (though of course that would be welcome). I think "functional testing" is more practical here, which is why I was thinking a quick(ish) merge would be nice - it'll let people play with it without having to set up a local server etc.

But thinking about it now, even when on the live site you still need to install my feature branch of nf-core tools to test it. So maybe it can wait until either that's ready, or I've added the functionality to launch directly from a pipeline on the website.

Phil

**Comment by ggabernet** [comment]
I was going to test your feature branch of tools, but not sure how to set up the local server, so this would help at least for me ;)

**Comment by ewels** [comment]
Merged :)

**Pull request merged**
