### PR TITLE
setup oldsite ci and iframe ready subpages.

### PR DESCRIPTION
**Pull request by mashehu**

### CODE REVIEW

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Review by ewels — APPROVED** [review]
I'll take your word for it 👍🏻  :)

**Review by ewels — COMMENTED** [review]
Maybe: Just update `header.php` instead of a new `slim_header.php` and remove all content that we don't need to pull in from iframe? To avoid duplicate pages.

Alternative (maybe easier): Set to ignore everything with robots / head meta, add a massive warning banner / auto-redirect to `header.php`.

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Pull request merged**
