### PR TITLE
Added contributor details and logo

### PR DESCRIPTION
**Pull request by AnnaSyme**

### CODE REVIEW

**Comment by ewels** [comment]
The white SVG logo is a bit funky here - seems to have a white background?

image

Also, there's no `description` for the institute..

**Comment by drpatelh** [comment]
I noticed that the description is missing for other institutions too. I'll create a separate PR adding that in.

**Comment by ewels** [comment]
Ah, the image in the PR is a `png`, but the website only loads `svg` images on the homepage.. So not sure where it came from? Wait - @apeltzer is pushing direct to master 😱 😆

**Comment by apeltzer** [comment]
Yeah I noticed that after merging this in and added a copy& paste description straight from their homepage, made a white SVG and made the color (PNG-SVG) a real SVG...

**Pull request merged**
