### PR TITLE
Added contributor info

### PR DESCRIPTION
**Pull request by drewjbeh**

### CODE REVIEW

**Comment by drpatelh** [comment]
Ah, sorry I should have said that the PR would have required review before merging. The branch protection rules werent enable for this repo for some reason. Ive done that now. Will need to submit a separate PR to fix the white logo, and to move the contributor listing to the end of the yaml as opposed to the beginning.

**Comment by drpatelh** [comment]
Will address these in https://github.com/nf-core/nf-co.re/pull/228

**Comment by drewjbeh** [comment]
Thanks, approved the changes.
Do I need to still upload the white logo in  a separate PR?

**Comment by drpatelh** [comment]
No probs. The corrected version should have been added to #228 . For any PRs to core repos such as the website we normally require an approving review by someone from @nf-core/core just as a full on sanity check. For pipeline repos things are more flexible for other contributors. 

We also have specific channels for each of these on Slack:
https://nf-co.re/join

**Pull request merged**
