### PR TITLE
fix highlightjs warning about html tags inside code blocks.

### PR DESCRIPTION
**Pull request by mashehu**
Not the most straightforward solution maybe, but it seems to do the job 😉

### CODE REVIEW

**Review by ewels — COMMENTED** [review]
This regex is making my head 🤯 a little. Doesn't the `|` mean OR, so the new section is essentially totally separate from the first? How does this work?

**Comment by mashehu** [comment]
I tried to find a regex to not catch things inside a `<pre>` tag, so I explicitly catch these elements, but then ignore them with the if clause. Is there a more php-typical way to do this?

**Comment by ewels** [comment]
So the regex doesn't look inside the `<pre>` tag because it already matched the entire thing? Smart!

Not sure off the top of my head how I would do it. Probably in a messier way than this. If it works then I'm happy 👍🏻 (maybe add a bit more verbose comment explaining how it works for when I forget this conversation).

**Review by ewels — APPROVED** [review]

**Comment by mashehu** [comment]
I tested it a bit more and it actually doesn't work like expected in all cases. I simplified it now, so it uses the old regex, but keeps checking if it is immediately inside a tag, which excludes them inside the code blocks (if they are not a string) or also inside headers, which is currently breaking some pages. To fix these I will merge this now, but maybe come back with a better solution 🤞🏻

**Review by ewels — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
