### PR TITLE
Added some FontAwesome to the homepage

### PR DESCRIPTION
**Pull request by ewels**
Messing around with the new FontAwesome Pro to add some nice new icons to the homepage:

image

---

image

### CODE REVIEW

**Comment by mashehu** [comment]
I find the two-color toolbox icon a bit off, because in my opinion the accent colors should be switched with the main color. But that is something FA has to fix 🙂. So my proposal would be to just use the normal one color fa-toolbox, to improve readability of the symbol.

**Comment by ewels** [comment]
[`fa-swap-opacity`](https://fontawesome.com/how-to-use/on-the-web/styling/duotone-icons#swapping-layers) to the rescue! 




Though actually you might be right that the solid version is still better:

**Comment by ewels** [comment]
Any suggestions for a better icon?

**Comment by mashehu** [comment]
Unfortunately not, the only one which came to my mind was the ball pile https://fontawesome.com/icons/ball-pile?style=regular, where the regular version looks a bit like a bunch of pipelines. but maybe I have too much fantasy there and a toolbox is actually the closest icon association.

**Comment by ewels** [comment]
I like where you're going with the ball pile icon @mashehu, but after playing with a couple it feels a bit busy and not super clear.. Might work with a big icon though. I think the toolbox is ok for now..

Thanks both!

**Comment by jfy133** [comment]
Ok I forgot to press comment: I think the full opacity toolbox is fine. I found the balls a bit too abstract.

**Comment by ewels** [comment]
Glad we're in agreement 😄

**Pull request merged**
