### PR TITLE
Bytesize transcripts

### PR DESCRIPTION
**Pull request by FranBonath**

### CODE REVIEW

**Comment by FranBonath** [comment]
@nf-core-bot fix linting

**Review by abhi18av — APPROVED** [review]
Looks good to merge ✅

**Comment by mribeirodantas** [comment]
Hey, @FranBonath. I will look at it today, while I listen again to the episodes, as I did for Bactopia. I think it's safer to do it like that before we merge if you don't mind.

**Comment by FranBonath** [comment]
I don't mind at all  @mribeirodantas :)

**Pull request merged**
