### PR TITLE
Dates and times correction

### PR DESCRIPTION
**Pull request by JoseEspinosa**
Dates were corrected since they were not correctly read.
Times also corrected to show time zone.

### CODE REVIEW

**Review by ewels — APPROVED** [review]

**Comment by ewels** [comment]
Yup, as you saw - the date strings are parsed as date objects, so stuff like `(TBC)` breaks the rendering :)

**Comment by ewels** [comment]
Another thing is that the event types use a controlled vocabulary - currently `hackathon`, `talk`, `poster` or `tutorial`. As a result, `workshop + hackathon` isn't styled properly. We should pick one of the four presets, or if we want we can add another (code [here](https://github.com/nf-core/nf-co.re/blob/436cd1707944cfeaaeed15f0881a5fb95654d830/public_html/events.php#L4-L15)).

Finally, it should be `nf-core` and not `nf_core` in the top page description 😉

**Comment by JoseEspinosa** [comment]
Couldn't have made more typos in a shorter text 😓

**Comment by ewels** [comment]
Hah, don't worry about it! We should probably add CI and stuff for this, there is no documentation or any way to know about these things without diving into the code and poking around. We haven't had so many contributors so far though so it hasn't really been an issue. But definitely not your fault 😉

**Pull request merged**
