### PR TITLE
GHGA contribution

### PR DESCRIPTION
**Pull request by nickhsmith**

### CODE REVIEW

**Comment by nickhsmith** [comment]
@nf-core-bot fix linting pretty please

**Comment by mashehu** [comment]
Can you please also add a white version of the logo?

**Comment by nickhsmith** [comment]
> Can you please also add a white version of the logo?

It's the same logo, but it should work on white and dark backgrounds.

**Comment by christopher-hakkaart** [comment]
> It's the same logo, but it should work on white and dark backgrounds.

It's for the rolling banner on the home page - it's better if they are all white.

**Comment by nickhsmith** [comment]
Done

> > It's the same logo, but it should work on white and dark backgrounds.
> 
> It's for the rolling banner on the home page - it's better if they are all white.

done

**Review by christopher-hakkaart — APPROVED** [review]
LGTM 👍

**Pull request merged**
