### PR TITLE
Update nf-core-contributors.yaml

### PR DESCRIPTION
**Pull request by yuifu**

### CODE REVIEW

**Comment by apeltzer** [comment]
Please also add a SVG file - similar to what @MaxUlysse did [here](https://github.com/nf-core/nf-co.re/pull/403)

**Comment by yuifu** [comment]
Thank you for your instruction. I added SVG files.

**Review by apeltzer — APPROVED** [review]

**Comment by apeltzer** [comment]
The white version isn't whity unfortunately - can you send one that is white?

**Comment by yuifu** [comment]
@apeltzer I put new image and made new PR https://github.com/nf-core/nf-co.re/pull/522

**Pull request merged**
