### PR TITLE
fix html encoding artefacts in schema

### PR DESCRIPTION
**Pull request by mashehu**
by decoding the affected strings before writing the object

### CODE REVIEW

**Comment by mashehu** [comment]
This would be one quick fix for #499. But it is by far not optimal, since already created schemas values would have to manually be touched once, to be re-encoded. Should we maybe fix this on the tools side in the build function, @ewels ?

**Review by ewels — APPROVED** [review]
Ok nice, so the whole issue is due to the `sanitize_html()` function? Then yes I think that this looks like a good fix. Haven't tested it, but assuming that you have I'm happy for this to be merged to at least avoid any future damage.

I think other fixes in tools etc can be in addition to this fix? Thoughts?

**Comment by mashehu** [comment]
Having thought more about it, maybe the tools part is not needed. We don't have so many schemas out in the wild yet, so a more manual fix should be doable. Either I go manually through them and look for incorrect encodings (`/` being the main culprit) and/or write a linter function for it.

But I will test this draft a bit more (especially the json preview) and will let you now, when I need a review.

**Comment by ewels** [comment]
Sounds good! 🚀

**Comment by ewels** [comment]
The issue reported two different kinds of encoding weirdness - the HTML entities, but also the `\/` escaping.. Is the latter a read herring, and just part of regular JSON?

**Comment by mashehu** [comment]
Yes, the second one is what I mentioned with the json preview. I figured it out: php's `json_encode()` is a bit too clever, but thankfully has an `JSON_UNESCAPED_SLASHES` option.

**Comment by ewels** [comment]
Nice! 🚀

**Comment by mashehu** [comment]
Okay, I had a deeper look into the problem: I was over-sanitizing the strings and without realizing that javascript+jQuery would already take care of the special characters in places, where we don't write direct html.

So, this PR should actually fix both problems mentioned in #499 and should automatically fix the incorrect json schemas if loaded once into the browser (because we write it into the text area in the php part => HTML entities are converted into the symbols => the javascript reads the text and doesn't reintroduce the html entities => win 🙂). But this part I can't competly test, unfortunately.

**Review by ewels — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
