### PR TITLE
add videos to the pipeline sidebar 

### LINKED ISSUE #1141: Side bar in pipeline page for video content
It would be nice to render video content in the sidebar for pipelines / other pages like modules etc to make them easier to find. We have amassed a number of pipeline-specific bytesize talks now and it would be nice link them on the website. The options to do this sort of thing in markdown or on Github in general are quite limited.

### PR DESCRIPTION
**Pull request by mashehu**
Requires a `youtube_embed` entry with the youtube link  in the header of README.md of the pipline.

Screenshot 2022-08-04 at 16 01 06

I also moved the youtube api loading into the script to get a more reliable loading

closes #1141 

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1224"></a>

### CODE REVIEW

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Review by ewels — APPROVED** [review]
Nice!

What do you think about having it set in the event page meta instead / as well? Wondering if it might be easier to update there (otherwise have to wait for a new release of the pipeline etc).

Phil

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Comment by mashehu** [comment]
Yes, I was also not happy that it would require a new pipeline release, but I didn't know that `$events` is actually already loaded even when outside the events pages. Changed it now accordingly. 

Should the `embed_at` tag already be expected to be an array or are we not assuming that they will appear in multiple pages?

**Comment by ewels** [comment]
Yeah if we can imagine it, it'll probably happen at some point. Also multiple videos per page..?

**Comment by mashehu** [comment]
Hmm, I'll leave this problems to future-me. Shouldn't be to difficult to change the implementation and good to have the feature out now. 

You can merge it, if you are happy like this, otherwise I can add the multi-video, multi-destination features next week.

**Pull request merged**
