### PR TITLE
Bytesize airrflow

### PR DESCRIPTION
**Pull request by FranBonath**
page for bytesize nf-core/airrflow on the 25th of October.
@nf-core-bot fix linting

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1404"></a>

### CODE REVIEW

**Comment by FranBonath** [comment]
@nf-core-bot fix linting

**Comment by FranBonath** [comment]
Don't know how I separate out the commits I made into separate PRs... Can I do it somehow now?

**Comment by mashehu** [comment]
make a new branch from master and cherry-pick the bytesize commit

**Review by ggabernet — APPROVED** [review]
LGTM

**Pull request merged**
