### PR TITLE
Teams notifications

### PR DESCRIPTION
**Pull request by atrigila**
Addressing https://github.com/nf-core/nf-co.re/issues/1455 but I need feedback if this is correct and also if this page is appropriate. 

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1717"></a>

### CODE REVIEW

**Comment by christopher-hakkaart** [comment]
Is Slack also supported? I haven't checked but it had a feeling it was?

**Comment by matthdsm** [comment]
Yes, slack should also be supported. If I'm not mistaken @Midnighter added that part, but it _should_  amount to the same thing

**Comment by matthdsm** [comment]
The selection for slack vs teams is done based on the url
https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/lib/NfcoreTemplate.groovy#L208

So the method for enabling the notification stays the same.

**Comment by matthdsm** [comment]
the docs for slack are here
https://api.slack.com/messaging/webhooks

So if you were to add that next to the teams ones I think it's good to go

**Review by matthdsm — APPROVED** [review]
Looks good to me 😄 Good work

**Comment by atrigila** [comment]
Thanks for the review @matthdsm @muffato @christopher-hakkaart :)

**Review by muffato — APPROVED** [review]

**Pull request merged**
