### PR TITLE
switch to dark scroll bars in dark mode

### PR DESCRIPTION
**Pull request by mashehu**
While trying to fix the ToC, I got too annoyed by the white scroll bars 🤷‍♂️
Firefox:
Screenshot 2020-07-30 at 14 16 09
Webkit:
Screenshot 2020-07-30 at 14 16 35

### CODE REVIEW

**Comment by ewels** [comment]
This makes the scroll bars more obvious and annoying for me (Chrome, OSX).

Before the change the scrollbars are darker and automatically disappear when not being scrolled:

before

After the change they are there all the time and are more obvious:

after

Similar behaviour in Firefox and Safari. I guess this is an operating-system thing?

**Comment by mashehu** [comment]
Ah, yes, I didn't test for cases when the OS hides scrollbars. Scrap this PR then. But interesting that your chrome bars are automatically dark. Which OS version and are you using a chrome theme?

**Comment by ewels** [comment]
* macOS Catalina 10.15.6 (`19G73`)
* Chrome 84.0.4147.89

No theme..

**Comment by mashehu** [comment]
okay, maybe I should finally update to Catalina (or Big Sur soon) then 🙂

**Pull request closed without merging**
