### PR TITLE
Add Refgenie usage documentation

### PR DESCRIPTION
**Pull request by mirpedrol**
Add Refgenie documentation after its implementation in [#1090](https://github.com/nf-core/tools/pull/1090)

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1199"></a>

### CODE REVIEW

**Comment by mashehu** [comment]
@mirpedrol, because https://github.com/nf-core/tools/pull/1090 has been merged, should we also merge this one, or should we give a disclaimer that it is dev only for now?

**Comment by mirpedrol** [comment]
Hi @mashehu, I was thinking of waiting until the new release, to avoid confusion. But it's also fine to add a disclaimer if you prefer :)

**Comment by mashehu** [comment]
Good. Do we have a trello board or milestone list for this release, so we can set this PR there as a reminder?

**Comment by mirpedrol** [comment]
We aren't using a board. I will have it in mind after the release :)

**Pull request merged**
