### PR TITLE
Hackathon: Add Quilt Data San Jose Co-Working Location

### PR DESCRIPTION
**Pull request by drernie**

### CODE REVIEW

**Comment by drernie** [comment]
Now that this is approved, what is the process to get it merged?

**Comment by mashehu** [comment]
You can just hit merge whenever you are ready 🙂

**Comment by drernie** [comment]
I don't have write access to this repo, just the code one. Which Slack channel should I use to ask?

**Comment by mashehu** [comment]
#github-invitations, but I merged it now

**Pull request merged**
