### PR TITLE
Add dynamic event element on index page.

### PR DESCRIPTION
**Pull request by mashehu**
Added a new current event card into the events page, which I then reuse on the index page (had to move a function from `events.php` into `functions.php` and the headings of all the events md files have to be parsed on every load of index.php (will probably be quicker when we have the events in a database 😉).

I am not sure if the triangle and gray background is really needed or if I should just add it to `homepage-header-contents`. Also the card feels a bit too waste full with the screen estate...

index page:
Screenshot 2021-03-11 at 18 31 18

Screenshot 2021-03-11 at 18 30 28

event page:
Screenshot 2021-03-11 at 18 36 32

### CODE REVIEW

**Comment by ewels** [comment]
Love it! Some speed thoughts from just the screengrabs:

* I find the square box and the angular triangle on the homepage a little jarring.. Can we do without the box there?
* The event time needs to be shown very prominently (I can't see it in the card at all?)
* The supersized fa-icon is awesome, but maybe slightly too much supersized to the extent that it becomes less clear what it is
* What happens if there are multiple links? Might need a dropdown box? Or better to just link to the event page instead?
* Homepage needs to say "Ongoing event" somewhere so that it's clear that's why it's there
* Is this only during an ongoing event? Do we want to show it a bit ahead of when an event actually starts?
  * Could maybe do it 30 mins before by default but make this customisable in the event, eg. so for the hackathon it shows from a few days ahead
  * Could have a countdown timer to the event start!
* Maybe bigger text and use of columns would make it less whitespacey on the homepage? I agree that there is quite a bit of space at the moment. Event page looks good as you have consistency with the other events, plus it has context.

This is super super cool 🚀

**Comment by mashehu** [comment]
I think I found a nicer layout for them. Removing the borders make them integrate better into the rest of the page I think:
Screenshot 2021-03-12 at 18 50 58
Screenshot 2021-03-12 at 18 49 28

Multiple links are now shown next to each other with some tricks, if there are too many.
Events longer than 5h (=whole day events) are now shown 5 days in advance.

**Comment by mashehu** [comment]
I think I found a nicer layout for them. Removing the borders make them integrate better into the rest of the page I think:
Screenshot 2021-03-12 at 18 50 58
Screenshot 2021-03-12 at 18 49 28

Multiple links are now shown next to each other with some tricks, if there are too many.
Events longer than 5h (=whole day events) are now shown 5 days in advance.

**Comment by mashehu** [comment]
I can make it a bit more compact with a smaller icon, but I think I am now more used to the larger version 🙂 
Screenshot 2021-03-12 at 19 18 01

**Comment by mashehu** [comment]
Now with "On-air" indicator in the navbar:
Screenshot 2021-03-15 at 11 05 15

**Comment by ewels** [comment]
Sorry for being slow @mashehu - will get to this ASAP. On the face of it I love the functionality, but want to have a play with some different designs on the homepage if that's ok. Just need to tear myself away from nf-core/tools for a moment to actually have a stab at it 😓

**Comment by ewels** [comment]
ps. Also happy to merge just to get this live if you're happy with code quality, then I can make my own PR at some point with any homepage tweaks that I want to try.

**Comment by mashehu** [comment]
okay, I'll merge it then. Feel free to have a stab at the design, I am not happy yet with the white space between the text and the label+button, but it looks even weirder if I make it narrower and it needs to grab your attention after all (I could say it is a mobile first design, because there it is more compact and nicer 😜).

**Comment by ewels** [comment]
Looking now, hold off on the merge as it hasn't already gone if that's ok 👍🏻

**Comment by ewels** [comment]
Ok, I had a bit of a play at reworking the display on the homepage. The code is pretty ugly sorry, but that's not new for the website repo 😓 

I meant to put this in a separate PR to your repo @mashehu, apologies for pushing directly to the PR. If you don't like it let me know and I'll branch it off and we can revert.

I rewrote the homepage so that it just picks one event to highlight - if there are ongoing events it picks the one with the latest start time (closest to now) or if upcoming the earliest (also closest to now). The main events page is unchanged so that will still highlight all, but I felt that it was too much for the homepage to have multiple and it shouldn't happen often anyway.

I then rewrote the output pretty much from scratch to be more integrated in the rest of the page, less boxy and with 3 columns. I refactored some of the other code for the events page to reuse the stuff like nice dates.

Upcoming events and Ongoing are differentiated by different headings and background icons in the left column. We could maybe also think about additional colours / font weights etc to make ongoing even more obvious.

There are a few variations for the right hand column:

* Upcoming - show a countdown timer on the right
* Ongoing - show the watch dropdown on the right
* Ongoing with an embed - show the embed on the right (buttons move to middle column)

Here come the obligatory screenshots:

### Upcoming event

localhost_8888_ (2)

### Ongoing event

localhost_8888_ (4)

### Ongoing, with new `youtube_embed` key

localhost_8888_ (3)

### "Watch now" Dropdown



### Dark mode

localhost_8888_ (5)


Let me know what you think!

**Comment by mashehu** [comment]
Very nice, it is so tidy now! 😍 

A few things I saw after a quick look:
- Date and time is too dark in dark mode
- For full day events (events longer than 5h), the element is shown 5 days in advance, but the countdown is only to the time not also the date (also, I think "Event starts in:" or "Starts in:" sounds better than "Event Countdown")
- On mobile it hides too much of the normal website and can therefore be confusing, maybe we can make the heading smaller (and the icon should be centered):
IMG_4574
- For ongoing events we should also show the "Event details" button.
- Very nice solution with the `youtube_embed`! 
- The dropdown should be a normal button, if there is only one element, saves the user one click and it is also clearer where to watch (I am actually not sure how often we will have an event with multiple links to watch at).
- Should we have the category badge just after the title (but not pulled right)? Looks a bit lost next to the date I think and probably helpful for not so clear event names.
- I think the big icon would be extra fancy, if we could cut it with a clip-path parallel to the triangle.

**Comment by ewels** [comment]
Yes all good points - I maybe fixed the days thing after you tried it?

I thought about clipping to the triangle but then decided it sounded too hard so didn't try 😅 

Also need to make `youtube_embed` handle lists of videos and then make the event page show them (remove current manual embeds).

**Comment by ewels** [comment]
Was also thinking that it would be nice to rethink the event YAML fields. At the moment we're sort of hijacking the `location` field as it was a quick and dirty fix when we moved online, but would be nice to have dedicated fields for Slides / DOI, YouTube, Bili Bili, Zoom and so on.

Each should probably have the option of a string or a list (eg. when there are multiple talks at an event) and each should be able to just take a url string or a dict with more options (text + URL).

Could also be nice to add custom FA icons for Bili Bili and DOI etc.

**Comment by ewels** [comment]
Can do all of this as a separate PR though, so will move to an issue ☝🏻

**Comment by ewels** [comment]
Ok, I think I'm done for now again @mashehu - hopefully cleared up all of the points you made above. More testing welcome but I think that we're getting close 😁 

> _Should we have the category badge just after the title (but not pulled right)? Looks a bit lost next to the date I think and probably helpful for not so clear event names._

I did that at first, but then the title is quite long and the date short which leaves a bit of an unbalanced hole of whitespace. So I moved it down into there.

**Comment by mashehu** [comment]
Now with nicely clipped background icon:
Screenshot 2021-03-17 at 21 17 14

**Comment by ewels** [comment]
Merging after approval on Slack ✅

**Pull request merged**
