### PR TITLE
add yt/figshare links to custom scripts bytesize

### PR DESCRIPTION
**Pull request by FranBonath**

### CODE REVIEW

**Review by christopher-hakkaart — APPROVED** [review]
👍

**Comment by christopher-hakkaart** [comment]
> @christopher-hakkaart Could you please also add your slides to the page?

I've published the slides on hackmd. Do you want them on figshare?

**Comment by FranBonath** [comment]
Do you want to make any more changes or can I merge? @mashehu @christopher-hakkaart

**Comment by mashehu** [comment]
@christopher-hakkaart do you have a link to the slides? I can then embed them.

**Pull request merged**
