### PR TITLE
Wrote script to pull GitHub issue statistics

### PR DESCRIPTION
**Pull request by ewels**
@drpatelh asked for statistics about how many GitHub issues and PRs are created - how many are replied to and what the response times are.

ask and ye shall recieve!

Currently this is just a script to pull the stats - nothing to display them yet. That will come next..

### CODE REVIEW

**Comment by ewels** [comment]
image

image

image

**Comment by ewels** [comment]
Ready to merge 👍 🎉

**Comment by drpatelh** [comment]
Bloody gorgeous :dancer:

**Comment by ewels** [comment]
Thanks! Script run manually on the server to do a first-pull of stats, and cron job set up to run at 2am every night.

**Comment by drpatelh** [comment]
Having thought about it a little do you think the response time plots would be better served as percentages?

**Comment by ewels** [comment]
Sure 😃 https://github.com/nf-core/nf-co.re/pull/162

**Pull request merged**
