### PR TITLE
Added publications page

### PR DESCRIPTION
**Pull request by ewels**
Closes nf-core/nf-co.re#261

localhost_8888_publications

### CODE REVIEW

**Comment by drpatelh** [comment]
Do you think we should add a DOI section for pipelines too? Would be nice to have all of this information findable on the same page rather than clicking countless links to figure out what you should be referencing. 

Could have granular details as to DOI per version too but that may involve fetching these from the Zenodo API if it exists? Or any other method you can think of that will work?

**Comment by MaxUlysse** [comment]
We should already have DOI for all released pipelines

**Comment by ewels** [comment]
I think that manually maintaining all pipeline Zenodo DOIs will be too much work and won't happen.

If we want this (and I think it could be a nice idea for quick reference, though not totally sure how often people will need a big list?) then I guess the best approach is to use the Zenodo API to fetch DOIs based on GitHub repository names. This is kind of unrelated to this PR, so maybe open a new issue for that 👍 

Phil

**Comment by ewels** [comment]
Ok, so can I merge this..? 😃

**Comment by drpatelh** [comment]
Sorry. Thought you were still working on it :+1:

**Pull request merged**
