### PR TITLE
Fix bioconda installation broken link

### PR DESCRIPTION
**Pull request by mribeirodantas**
Fix broken link for installation of conda

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1215"></a>

### CODE REVIEW

**Comment by maxulysse** [comment]
I think the correct link for bioconda is now `https://bioconda.github.io/#usage`
Not the one from the conda docs

**Comment by mribeirodantas** [comment]
I don't remember how the broken link looked like, but if you click on _install conda_ in the link you provided, it directs to the link I updated in the commit. Do you remember how it used to look like before the link got broken?

**Comment by mribeirodantas** [comment]
Oh, you're right, @maxulysse. Just now I realised my mistake, sorry 😅

**Review by ggabernet — APPROVED** [review]
Looks good to me, thanks for the fix!

**Pull request merged**
