### PR TITLE
Added header link to google groups. New contact section.

### PR DESCRIPTION
**Pull request by ewels**
email

### CODE REVIEW

**Comment by matq007** [comment]
What about using google's default [icon](https://www.ryerson.ca/content/dam/google/teach-with-google-apps/communication-tools/google-groups-1.png)?

**Comment by matq007** [comment]
Suggestion: what about using Google's default [icon](https://www.ryerson.ca/content/dam/google/teach-with-google-apps/communication-tools/google-groups-1.png)?

**Comment by ewels** [comment]
Yes, I started with that one actually. The nav bar icons are pretty small though and it wasn’t super clear. Additionally, I figured that most people will use google groups as an email list and not really care about the provider, so are more likely to be looking for an email icon.

Could revisit though. I’ll post a screenshot of it with the groups icon later if I get a chance 👍🏻

**Comment by ewels** [comment]
image

localhost_8888_

localhost_8888_ 1

**Comment by MaxUlysse** [comment]
I prefer with the google groups icon

**Comment by ewels** [comment]
Updated..

**Comment by matq007** [comment]
LGTM 👍

**Pull request merged**
