### PR TITLE
Create seqera-cloud-series-azure.md

### PR DESCRIPTION
**Pull request by evanfloden**
Adding in Nextflow on Azure event for later this week. Thanks!

### CODE REVIEW

**Comment by evanfloden** [comment]
Open to any suggestions on content and formatting.

**Comment by MaxUlysse** [comment]
Do you have a Youtube link as well?

**Comment by evanfloden** [comment]
> Do you have a Youtube link as well?

No Youtube link currently. Will add after we release the recording 👍

**Review by apeltzer — APPROVED** [review]
Think content wise this looks good - can still update with Youtube & other links once the recording is available, I think ...?

**Pull request merged**
