### PR TITLE
Adding Whitehead Institute as contributor

### PR DESCRIPTION
**Pull request by chlazaris**
I updated the YAML file and added two .svg files with the Whitehead logo. Please, feel free to let me know if any changes are required. Thank you!

### CODE REVIEW

**Review by apeltzer — APPROVED** [review]
Looks good 💪

**Comment by chlazaris** [comment]
Thank you @apeltzer! Is there an issue with the logo files (WIBR.svg)? They appear fine on my computer but not on GitHub or the nfcore collaborators webpage. Let me know if I could do something about it

**Comment by ewels** [comment]
Hi @chlazaris - I just noticed this as well, I'm not sure why. I'll look into it.

Note that although the filenames are SVG, the logo is still a raster PNG embedded in the SVG file. Do you have a vector version? I'll take a look on the web to see what I can find as well.

It looks like the logo on https://wi.mit.edu/ is different - is this intentional or was the logo updated?

image

**Comment by ewels** [comment]
Looks like the logo file is on the website properly: https://nf-co.re/assets/img/contributors-colour/WIBR.svg

I think that there's something weird with the SVG - probably that the logo is way off the SVG canvas so is being cropped. If you highlight the web page contents you can see that the image is there, it's just empty:

image

So basically we need to replace the SVG logo files.. I'll wait until I hear back about whether the logo was updated above ☝🏻 

If it is the new logo then here is a white SVG version: https://wi.mit.edu/themes/custom/whitehead/logo.svg (can make a coloured version from this quite easily). Colour code should be `rgb(55, 4, 255);` based on this logo: https://wi.mit.edu/themes/custom/whitehead/dist/images/logo.svg

**Comment by chlazaris** [comment]
Thank you very much for your reply, Phil.

Whitehead has now changed the logo to the one you found.
I have uploaded the white and colored version to the corresponding
directories and I made a pull request. The .svg files look OK on Photoshop
but feel free to let me know if there are any issues with the dimensions
etc. that you would like me to fix.

Thank you for your help.

Best Regards,

Harris

**Pull request merged**
