### PR TITLE
New Community page

### PR DESCRIPTION
**Pull request by ewels**
This is quite a big one, mostly reorganising existing content...

* Moved the contributing institution map and list to a new page: Community
* Added to this page a list of GitHub avatars scraped from the total list of all contributors (random order)
* Added a "Contributor Leaderboard" to the Statistics page, showing how many commits every contributor has done
* Rejigged the text in the now much-smaller About page and added a section listing the admin team.

image

----

image

---

image

### CODE REVIEW

**Comment by MaxUlysse** [comment]
This look quite impressive, quick questions, about the contributors list (the one with the github avatar)
- How is it sorted ? (it doesn't look alphabetical)
- There are only 26 public members of the nf-core organisation, yet, you publish all 70 members. Is it allowed?

**Comment by ewels** [comment]
It’s sorted randomly (deliberately) - refresh and it’ll shuffle again..

Other contributions would be good to add in the future. I’m not pulling this yet though.

People are private by default, I’m assuming that everyone _wants_ to be public. I guess if we’re worried I could set up an automated email to email private members every day asking them to change it or remove themselves from the org?

**Comment by MaxUlysse** [comment]
I'm guessing it might be worth discussing, but sending a daily reminder might be a tiny bit too much I think ;-)

**Comment by ewels** [comment]
hah, sorry - daily because that's when the script runs that pulls the list. Yes, that is maybe a fraction spammy.

**Pull request merged**
