### PR TITLE
New schema structure - Auto docs

### PR DESCRIPTION
**Pull request by ewels**
Continuation of https://github.com/nf-core/nf-co.re/pull/464

Only really the last two commits - the rest is merging in upstream changes from `master`.

### CODE REVIEW

**Comment by ewels** [comment]
Interesting diff for the PR here: https://github.com/nf-core/nf-co.re/pull/468/files/f83b603b87a503fd5dc68333a448fe07a60ee09f..42bbc30143b2300e64df71bc4db6a8edcc952aea

Note that shows that I messed up a merge conflict fix. Note that I chose the diffs relatively arbitrarily @mashehu, so you might want to check that you agree with my choices (you can see what I went for in the diff as it shows the merge conflict markers..!)

**Comment by ewels** [comment]
Ah yeah, I noticed that on a previous PR somewhere. I'll look into it now 👍🏻

**Comment by ewels** [comment]
I think this must have been something to do with the way that PHP figures out which file to import - changing the filename so that it didn't clash with the other `stats.php` seemed to fix the error.. ❔

**Comment by ewels** [comment]
The now-functional stats page looked a bit odd now that it's wider. I added in the fancy sidebar so that it has more visual consistency with the other pipeline pages.

**Comment by mashehu** [comment]
Yes, everything works for me now.

**Pull request merged**
