### PR TITLE
Document Nextflow DSL2 configuration issue with parameters and custom config files

### PR DESCRIPTION
**Pull request by jfy133**
As discusse dhere: https://nfcore.slack.com/archives/CE6SDBX2A/p1674599225438509

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1558"></a>

### CODE REVIEW

**Comment by jfy133** [comment]
@nf-core-bot fix linting

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by FriederikeHanssen** [comment]
Actually maybe adding a note that it can easily be generated using the website (for anyone that doesn't want to manually write a json file :D

**Comment by jfy133** [comment]
Done!

**Review by grst — APPROVED** [review]
LGTM!

**Comment by jfy133** [comment]
@nf-core-bot fix linting

**Pull request merged**
