### PR TITLE
JSON schema build

### PR DESCRIPTION
**Pull request by ewels**
New page to give interactive GUI for rearranging and building pipeline schema files.

Works in conjunction with `nf-core schema build`, see https://github.com/nf-core/tools/pull/584

### CODE REVIEW

**Comment by ewels** [comment]
Quick gifs of how this works:

---

nf-core-schema-build

---

nf-score-schema-web

---

**Comment by ewels** [comment]
What, you're not going to pick through [939 lines](https://github.com/nf-core/nf-co.re/pull/329/files#diff-50fe998361a51c27bb42f5df30467eea) of custom JavaScript code?? 😆

**Comment by drpatelh** [comment]
Oh, Im sorry, I misunderstood. Did you want to merge this before Xmas?

**Comment by apeltzer** [comment]
> 
> 
> Oh, Im sorry, I misunderstood. Did you want to merge this before Xmas?

Going to frame this and put it in my office :-D

**Pull request merged**
