### PR TITLE
Add UC Berkeley as contributor

### PR DESCRIPTION
**Pull request by heuermh**
Not sure if we have SVG logos, will have to check

### CODE REVIEW

**Comment by apeltzer** [comment]
How about this one? https://commons.wikimedia.org/wiki/File:University_of_California,_Berkeley_logo.svg

**Comment by heuermh** [comment]
Thanks @apeltzer!  Added, pushed, and squashed commits

**Comment by drpatelh** [comment]
Yeah, I was about to do merge this but realised that my colour-blindness may be a problem.

**Comment by heuermh** [comment]
Thank you, @ewels @drpatelh

**Pull request merged**
